artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/49087a0287ea484a806e85487f9d5995/artifacts
end_time: 1746864805221
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 49087a0287ea484a806e85487f9d5995
run_name: baseline_mean
run_uuid: 49087a0287ea484a806e85487f9d5995
source_name: ''
source_type: 4
source_version: ''
start_time: 1746864805173
status: 4
tags: []
user_id: gourimenon8
