artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/8847f1dc54834b32bafaf68861c2a9c3/artifacts
end_time: 1746875704456
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8847f1dc54834b32bafaf68861c2a9c3
run_name: lgbm_28lags_full
run_uuid: 8847f1dc54834b32bafaf68861c2a9c3
source_name: ''
source_type: 4
source_version: ''
start_time: 1746875674455
status: 3
tags: []
user_id: gourimenon8
