artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/de80e6c27fd54620998323fce8a9bb6a/artifacts
end_time: 1746857615866
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: de80e6c27fd54620998323fce8a9bb6a
run_name: lgbm_28lags_full
run_uuid: de80e6c27fd54620998323fce8a9bb6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746857583315
status: 3
tags: []
user_id: gourimenon8
