artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/b95bd1ffeeae47b1bf0a4d284b14fcfa/artifacts
end_time: 1746861425713
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b95bd1ffeeae47b1bf0a4d284b14fcfa
run_name: baseline_mean
run_uuid: b95bd1ffeeae47b1bf0a4d284b14fcfa
source_name: ''
source_type: 4
source_version: ''
start_time: 1746861425646
status: 3
tags: []
user_id: gourimenon8
