artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/ce419fa5cee74cd2b7ba3702e43b2be5/artifacts
end_time: 1746860373916
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ce419fa5cee74cd2b7ba3702e43b2be5
run_name: lgbm_28lags_full
run_uuid: ce419fa5cee74cd2b7ba3702e43b2be5
source_name: ''
source_type: 4
source_version: ''
start_time: 1746860341859
status: 3
tags: []
user_id: gourimenon8
