artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/7383a91b33384f698c024ae821940fca/artifacts
end_time: 1746856163459
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7383a91b33384f698c024ae821940fca
run_name: lgbm_28lags_full
run_uuid: 7383a91b33384f698c024ae821940fca
source_name: ''
source_type: 4
source_version: ''
start_time: 1746856135599
status: 3
tags: []
user_id: gourimenon8
