artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/b257a511c80b4f37a0e407dd9a005c95/artifacts
end_time: 1746846119158
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b257a511c80b4f37a0e407dd9a005c95
run_name: lgbm_top10_lags
run_uuid: b257a511c80b4f37a0e407dd9a005c95
source_name: ''
source_type: 4
source_version: ''
start_time: 1746846028279
status: 3
tags: []
user_id: gourimenon8
