artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/bd11615c02984cd3bbc184a541b05a02/artifacts
end_time: 1746876298413
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bd11615c02984cd3bbc184a541b05a02
run_name: lgbm_top10_lags
run_uuid: bd11615c02984cd3bbc184a541b05a02
source_name: ''
source_type: 4
source_version: ''
start_time: 1746876124916
status: 3
tags: []
user_id: gourimenon8
