artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/d9e6818e06794392841cdc4c9e5dbf14/artifacts
end_time: 1746862624295
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d9e6818e06794392841cdc4c9e5dbf14
run_name: lgbm_28lags_full
run_uuid: d9e6818e06794392841cdc4c9e5dbf14
source_name: ''
source_type: 4
source_version: ''
start_time: 1746862576116
status: 3
tags: []
user_id: gourimenon8
