artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/d66782ed98af4d4ab0d23c971e048708/artifacts
end_time: 1746857618492
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d66782ed98af4d4ab0d23c971e048708
run_name: lgbm_top10_lags
run_uuid: d66782ed98af4d4ab0d23c971e048708
source_name: ''
source_type: 4
source_version: ''
start_time: 1746857615890
status: 4
tags: []
user_id: gourimenon8
