name: Inference

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-inference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run inference
        run: python src/inference.py
