aliases: []
creation_timestamp: 1746846069528
current_stage: None
description: null
last_updated_timestamp: 1746846069528
name: citibike_model_8 Ave _ W 31 St
run_id: b257a511c80b4f37a0e407dd9a005c95
run_link: null
source: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/b257a511c80b4f37a0e407dd9a005c95/artifacts/model_8
  Ave _ W 31 St
status: READY
status_message: null
storage_location: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/b257a511c80b4f37a0e407dd9a005c95/artifacts/model_8
  Ave _ W 31 St
user_id: null
version: 1
