artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/33a0f80992fd4bdabc1cb6dcac0b3b0a/artifacts
end_time: 1746852746438
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 33a0f80992fd4bdabc1cb6dcac0b3b0a
run_name: lgbm_top10_lags
run_uuid: 33a0f80992fd4bdabc1cb6dcac0b3b0a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746852654769
status: 3
tags: []
user_id: gourimenon8
