aliases: []
creation_timestamp: 1746852715520
current_stage: None
description: null
last_updated_timestamp: 1746852715520
name: citibike_model_Broadway_W_25_St
run_id: 33a0f80992fd4bdabc1cb6dcac0b3b0a
run_link: null
source: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/33a0f80992fd4bdabc1cb6dcac0b3b0a/artifacts/model_Broadway_W_25_St
status: READY
status_message: null
storage_location: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/33a0f80992fd4bdabc1cb6dcac0b3b0a/artifacts/model_Broadway_W_25_St
user_id: null
version: 1
