artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/a45bf838df7e41a6a4184e609bb2599d/artifacts
end_time: 1746856135599
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a45bf838df7e41a6a4184e609bb2599d
run_name: baseline_mean
run_uuid: a45bf838df7e41a6a4184e609bb2599d
source_name: ''
source_type: 4
source_version: ''
start_time: 1746856135520
status: 3
tags: []
user_id: gourimenon8
