artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/5a389a2c2514427ead9b78e2612cae71/artifacts
end_time: 1746875674321
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5a389a2c2514427ead9b78e2612cae71
run_name: baseline_mean
run_uuid: 5a389a2c2514427ead9b78e2612cae71
source_name: ''
source_type: 4
source_version: ''
start_time: 1746875674112
status: 3
tags: []
user_id: gourimenon8
