artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/bc9697dac80d455190b2cf15f0901fd3/artifacts
end_time: 1746863746445
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bc9697dac80d455190b2cf15f0901fd3
run_name: lgbm_28lags_full
run_uuid: bc9697dac80d455190b2cf15f0901fd3
source_name: ''
source_type: 4
source_version: ''
start_time: 1746863704804
status: 3
tags: []
user_id: gourimenon8
