artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/e499361720e740ed929ac4680d423973/artifacts
end_time: 1746876066271
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e499361720e740ed929ac4680d423973
run_name: baseline_mean
run_uuid: e499361720e740ed929ac4680d423973
source_name: ''
source_type: 4
source_version: ''
start_time: 1746876066149
status: 3
tags: []
user_id: gourimenon8
