artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/7d3efd7a7467455fa639f6bd1762b796/artifacts
end_time: 1746856858442
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7d3efd7a7467455fa639f6bd1762b796
run_name: lgbm_28lags_full
run_uuid: 7d3efd7a7467455fa639f6bd1762b796
source_name: ''
source_type: 4
source_version: ''
start_time: 1746856822346
status: 3
tags: []
user_id: gourimenon8
