artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/b1060635c1dd41f7afe38e4a3ce31085/artifacts
end_time: 1746863749579
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b1060635c1dd41f7afe38e4a3ce31085
run_name: lgbm_top10_lags
run_uuid: b1060635c1dd41f7afe38e4a3ce31085
source_name: ''
source_type: 4
source_version: ''
start_time: 1746863746763
status: 4
tags: []
user_id: gourimenon8
