artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/5416c6cdede54954ab85d47b2de9f708/artifacts
end_time: 1746864175091
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5416c6cdede54954ab85d47b2de9f708
run_name: lgbm_28lags_full
run_uuid: 5416c6cdede54954ab85d47b2de9f708
source_name: ''
source_type: 4
source_version: ''
start_time: 1746864146631
status: 3
tags: []
user_id: gourimenon8
