artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/033641908613476db14024a41be39ccf/artifacts
end_time: 1746864482239
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 033641908613476db14024a41be39ccf
run_name: lgbm_28lags_full
run_uuid: 033641908613476db14024a41be39ccf
source_name: ''
source_type: 4
source_version: ''
start_time: 1746864439768
status: 3
tags: []
user_id: gourimenon8
