artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/f608e010e81c44a29d59feef0dd988ed/artifacts
end_time: 1746856178825
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f608e010e81c44a29d59feef0dd988ed
run_name: lgbm_top10_lags
run_uuid: f608e010e81c44a29d59feef0dd988ed
source_name: ''
source_type: 4
source_version: ''
start_time: 1746856163498
status: 4
tags: []
user_id: gourimenon8
