artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/e90bcca9cb02435d89a3ea76523fc291/artifacts
end_time: 1746864146625
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e90bcca9cb02435d89a3ea76523fc291
run_name: baseline_mean
run_uuid: e90bcca9cb02435d89a3ea76523fc291
source_name: ''
source_type: 4
source_version: ''
start_time: 1746864146555
status: 3
tags: []
user_id: gourimenon8
