artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/fdb14ea5877f489dbd9dd7092375316a/artifacts
end_time: 1746861465100
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fdb14ea5877f489dbd9dd7092375316a
run_name: lgbm_28lags_full
run_uuid: fdb14ea5877f489dbd9dd7092375316a
source_name: ''
source_type: 4
source_version: ''
start_time: 1746861425721
status: 3
tags: []
user_id: gourimenon8
