artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/5ac12201166b44e5bea077dff1f8973b/artifacts
end_time: 1746860341859
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5ac12201166b44e5bea077dff1f8973b
run_name: baseline_mean
run_uuid: 5ac12201166b44e5bea077dff1f8973b
source_name: ''
source_type: 4
source_version: ''
start_time: 1746860341789
status: 3
tags: []
user_id: gourimenon8
