artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/585bb9594abc43b09982439119f335e8/artifacts
end_time: 1746864930426
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 585bb9594abc43b09982439119f335e8
run_name: lgbm_28lags_full
run_uuid: 585bb9594abc43b09982439119f335e8
source_name: ''
source_type: 4
source_version: ''
start_time: 1746864885314
status: 3
tags: []
user_id: gourimenon8
