aliases: []
creation_timestamp: 1746848504741
current_stage: None
description: null
last_updated_timestamp: 1746848504741
name: citibike_model_University Pl _ E 14 St
run_id: 80123d2c505b4c88b9b329669a2f47d5
run_link: null
source: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/80123d2c505b4c88b9b329669a2f47d5/artifacts/model_University
  Pl _ E 14 St
status: READY
status_message: null
storage_location: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/80123d2c505b4c88b9b329669a2f47d5/artifacts/model_University
  Pl _ E 14 St
user_id: null
version: 2
