artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/5df957ed94a244a9b7a551ba91f553ba/artifacts
end_time: 1746860954307
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5df957ed94a244a9b7a551ba91f553ba
run_name: baseline_mean
run_uuid: 5df957ed94a244a9b7a551ba91f553ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1746860954203
status: 3
tags: []
user_id: gourimenon8
