artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/cd6a6e0fa3ca49bbb3417d17d3105d2f/artifacts
end_time: 1746863704789
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: cd6a6e0fa3ca49bbb3417d17d3105d2f
run_name: baseline_mean
run_uuid: cd6a6e0fa3ca49bbb3417d17d3105d2f
source_name: ''
source_type: 4
source_version: ''
start_time: 1746863704689
status: 3
tags: []
user_id: gourimenon8
