artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/907c623f2bd646deacf003439b3eb397/artifacts
end_time: 1746875315336
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 907c623f2bd646deacf003439b3eb397
run_name: lgbm_28lags_full
run_uuid: 907c623f2bd646deacf003439b3eb397
source_name: ''
source_type: 4
source_version: ''
start_time: 1746875278561
status: 3
tags: []
user_id: gourimenon8
