artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/47b189cc9acd46c3ac9dc3caa5c8c233/artifacts
end_time: 1746848390539
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 47b189cc9acd46c3ac9dc3caa5c8c233
run_name: baseline_mean
run_uuid: 47b189cc9acd46c3ac9dc3caa5c8c233
source_name: ''
source_type: 4
source_version: ''
start_time: 1746848390412
status: 3
tags: []
user_id: gourimenon8
