artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/ebf2eba4c4ee476d9ff4b9d93ea932a0/artifacts
end_time: 1746857224996
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ebf2eba4c4ee476d9ff4b9d93ea932a0
run_name: lgbm_28lags_full
run_uuid: ebf2eba4c4ee476d9ff4b9d93ea932a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1746857191984
status: 3
tags: []
user_id: gourimenon8
