artifact_location: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0
creation_time: 1746845965188
experiment_id: '0'
last_update_time: 1746845965188
lifecycle_stage: active
name: Default
