artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/2e00d8fecfb94b8dbfe4752c9cb8e2ab/artifacts
end_time: 1746864176735
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2e00d8fecfb94b8dbfe4752c9cb8e2ab
run_name: lgbm_top10_lags
run_uuid: 2e00d8fecfb94b8dbfe4752c9cb8e2ab
source_name: ''
source_type: 4
source_version: ''
start_time: 1746864175305
status: 4
tags: []
user_id: gourimenon8
