artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/2dc662d3a29949d1ab6dab3c9e3c9243/artifacts
end_time: 1746866787856
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2dc662d3a29949d1ab6dab3c9e3c9243
run_name: lgbm_top10_lags
run_uuid: 2dc662d3a29949d1ab6dab3c9e3c9243
source_name: ''
source_type: 4
source_version: ''
start_time: 1746866628699
status: 3
tags: []
user_id: gourimenon8
