artifact_uri: file:C:/gouri/MLops/citibike-forecasting/https/x3a/dagshub.com/gourimenon8/citybike-forecasting.mlflow/0/13ccc26681ee49bca885b4bb23055a18/artifacts
end_time: 1746865858777
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 13ccc26681ee49bca885b4bb23055a18
run_name: lgbm_top10_lags
run_uuid: 13ccc26681ee49bca885b4bb23055a18
source_name: ''
source_type: 4
source_version: ''
start_time: 1746865698236
status: 3
tags: []
user_id: gourimenon8
