name: Model Training

on:
  schedule:
    - cron: '0 4 1 * *'
  workflow_dispatch:

jobs:
  train-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run training
        run: python src/train.py
