name: Model Training

on:
  workflow_dispatch:
  push:
    paths:
      - "src/train.py"
      - "src/modeling.py"

jobs:
  model-training:
    runs-on: ubuntu-latest
    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train and Track Models
        run: |
          python src/train.py
          python src/infer.py