HOPSWORKS_API_KEY = "btW1GPYSCDQGXinp.Wjhc9xTW9pwsO0hXAR2j2vAwTUCAg6ZvGtTKdrhg3zBhWOE6xrttjfEd4p9tGz7R"
MLFLOW_TRACKING_USERNAME = "gourimenon8"
MLFLOW_TRACKING_PASSWORD = "15f1ef6bcb367ade4aec24ebd3dd8ff739995e91"
MLFLOW_TRACKING_URI = "https://dagshub.com/gourimenon8/citybike-forecasting.mlflow"